### ISSUE TITLE
Errors at the launch jar

### ISSUE THREAD

**Issue by obcardinal** [LuigiCerone/GameProject#1]
1. I try execute this line:
```
$ mysql -u gaming -p src/gaming.sql
```
I have issue:
```
ERROR 1049 (42000): Unknown database 'src/gaming.sql'
```

2. After running ``sql``with command:
```
$ source src/gaming.sq
```
And launch jar, I try registration. After click on the button of register, I have an exception about database 'Gaming' not found. At the ``sql`` file create 'gaming' database.
Rename database from ``sql`` 'gaming' to 'Gaming'.

**Comment by LuigiCerone** [comment]
1. Hi, yes you are right,
`$ mysql -u gaming -p src/gaming.sql`
should be
`$ mysql -u gaming -p < src/gaming.sql`

2. Fixed. Thanks
